name: Create release package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Download the Sphinx Rijkshuisstijl theme
        run: gh release download --clobber -D docs/ --repo minvws/icore-manon-sphinx-theme --pattern 'sphinx-rijkshuisstijl*.zip'
        env:
          GH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}

      - name: Setup node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run build all
        run: make all

      - name: Copy to public folder
        run: cp -R ./build/html ./public

      - name: Add version file
        run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > public/version.json'

      - name: Create tar
        run: tar -czf gfmodules-functional-documentation_${{ env.RELEASE_VERSION }}.tar.gz public/

      - name: Upload release tar
        uses: actions/upload-artifact@v4
        with:
          name: gfmodules-functional-documentation_${{ env.RELEASE_VERSION }}
          path: gfmodules-functional-documentation_${{ env.RELEASE_VERSION }}.tar.gz
